language: node_js
node_js:
- '4'
branches:
  only: master
before_script:
- npm install -g gulp
- npm install -g bower
- bower install
script: bash ./deploy.sh
env:
  global:
  - GH_REF: github.com/jonatasleon/gerador-de-voto.git
  - secure: "pZtU3K9K3hrkpTjKME7kYHU/1Iw9onKCInA9yjdDtR0Ww4GXz7dl68+z71gUgcM2vDI0YMzb7wAXvX0w0kuOvbV/c5brRWwiHA0LdxMEZszheCEP7zBGVuWpX+PA+EjxecB8hr0YRDt9kW+ufKhyAYHB6Dz4e15zdt5WZVeeiEfxUXWrbielR+iw8LILeL9HCmu4A8TbBlxPYE5zlhtZXNH20EQ7w4cIsORTu9WWJBTmVjy/ScnEAICnVI7sgU5c3Yl50I/u0tQC17ynCZ7YI6mziVXHTUrxH+dyMddeWS++v/wqEN7uRB2qvLFAUwYOYTIS/Sb2N4CiMsTQ2OfuSIE0q/R2bCZzmufPqTbdRZYK8oA39LQiMANnJyQWO3q8pBU21eOQyuVqV7ndp5lHnrIEHKdFrGP2ZxO0ulIM1e/EtZdBU70g6eiP9xFnjq6XduUz6BtPZAEiTPKWca50nOyoApqB/S4EnJRNfbyNFxTa9db6EnNfgfCA582Gc+KDoikZHAm07Ze4oW+nQDB38Scwt8M++rzXc35Nzn7Crp5EM3PmbI0ykSnEZa4aED1cuYbZ+aPVdVbe4sLdULAjImXjRpu7DGkpaPSWJXntg3b9OYlAw2d0Rf6ul4X/j5YAzQQ9Jg7Nbe0b5qfuRtdLjTrODgmh3hFBT0+ndCyGhuw="
