language: node_js
node_js:
- '4'
branches:
    only: master
before_script:
- npm install -g gulp bower
- npm install
- bower install
script: bash ./deploy.sh
env:
    global:
    - GH_REF: github.com/jonatasleon/gerador-de-voto.git
    - secure: "qfAT6LheNdoD20BZFNTpmUg4IexkkLVD+WxMZPRcbbNtiaWdXtcYFDPlitKc28tg1H4YCSqRjNCzBbSioMwJmcItXt0lH28dzgNkEN1NBdaEgYMai3YFkYlrt/lFazxw42o/CyhLXioiiKswDk+al3BOfMYMxbWlN6l1UXgIWANXvay99F/gktlP7E/yQwvOosT9yFcngoXo2vSm5tdlD5dUdaw9XF2tGjW1J9i6s8iEACIQC9D1t9ijpn5Dm5+mIrj6wDlPdBh+kz48UOeXkhJYH+6d/KKVfXMij7wqtbg3u5ibs6AmHA1o1AkXnnk0rPqgHQ+YwdZS7eLz8FlmQ2cgk8eNbZaDmhgEIvEafnnWvJXI7NdNi8DIr2K5MsWXxZ83t44YetW0y6Rok45JNHM4re/7n69L6dAqdQci/1d0GfnK6PijhUdQ3vLrStYaYtlQuaySrrQSjnU6ALcTsgu5XoJq/8v/xTzHhjxaxkzye1PYzIjJYsGyk4Wl8uHQQVpTbrylvtKu1bNn+qLAtyHJXIsTyZuktPLiuZFJDpkuX64stkS2mmLtH5Z6xkeutwXMG3K6IHTyfmWuUbphe5y7Ste4MNAgpkvH8SzeqO5ZTEVYhn2qmnuILKKJxxZbA4Z7EByXLNIK0Mutco/zzbw8M+qkAO/hC3D1Coklm74="
